#include "Predef.h"

const char *predef =
  "# char sets\n"
  "any       = 0 .. 256 # Any character in the alphabet. \n"
  "ascii     = 0 .. 127 # Ascii characters. 0..127 \n"
  "extend    = 0 .. 256 # Ascii extended characters. This is the range -128..127 for signed alphabets and the range 0..255 for unsigned alphabets. \n"
  "lower     = 'a' .. 'z' # Lowercase characters. [a-z] \n"
  "upper     = 'A' .. 'Z' # Uppercase characters. [A-Z] \n"
  "digit     = '0' .. '9' # Digits. [0-9] \n"
  "alpha     = upper | lower # Alphabetic characters. [A-Za-z] \n"
  "alnum     = digit | alpha # Alpha numerics. [0-9A-Za-z] \n"
  "xdigit    = digit | 'A' .. 'F' | 'a' .. 'f' # Hexadecimal digits. [0-9A-Fa-f] \n"
  "cntrl     = 0 .. 31 # Control characters. 0..31 \n"
  "graph     = '!' .. '~' # Graphical characters. [!-~] \n"
  "print     = ' ' .. '~' # Printable characters. [ -~] \n"
  "punct     = '!' .. '/' | ':' .. '@' | ']' .. '`' | '{' .. '~' # Punctuation. Graphical characters that are not alphanumerics. \n"
  "null      = 0\n"
  "tab       = 9  # tabulation\n"
  "lf        = 10 # line feed\n"
  "ff        = 12 # form feed\n"
  "cr        = 13 # carriage return\n"
  "eol       = cr? lf # unix or window$ end line\n"
  "vert_tab  = 11 # vertical tab\n"
  "space     = tab | vert_tab | ff | lf | cr # Whitespace. [\\t\\v\\f\\n\\r ] \n"
  "zlen      = '' # Zero length string\n"
  "end       = { end: inp_cont = &&end; return false; } any** # \n"

  "# mandatory arg: val (e.g. unsigned_int_reader[ val = 'content_length' ])\n"
  "uint =\n"
  "    _add_attr[ 'unsigned val;' 'sipe_data->val = 0;' ] \n"
  "    digit { sipe_data->val = *data - '0'; }\n"
  "    ( digit { sipe_data->val = 10 * sipe_data->val + ( *data - '0' ); } )**\n"
  ;
